version: 2

jobs:
  validate:
    docker:
      -
        image: finalgene/hadolint:latest
    working_directory: /app
    steps:
      - checkout
      - setup_remote_docker
      -
        run:
          name: Validate Dockerfile
          command: |
            hadolint Dockerfile

  build:
    docker:
      -
        image: docker:18.05.0-ce-git
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      -
        run:
          name: Build application Docker image
          command: |
            docker build .
      -
        run:
          name: List created images
          command: |
            docker images

workflows:
  version: 2
  validate_and_build:
    jobs:
      - validate
      - build:
          requires:
            - validate
