name: Validate Dockerfile

on:
  push:
    branches:
      - '*'

jobs:
  docker:
    name: Validate Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Lint dockerfile
        uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: Dockerfile
